org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

enable_lwjglx=true

mod_version=1.15.3
root_package=net.bdew
mod_id=bdlib
mod_name=BD Lib
mod_description=
mod_url=https://bdew.net/mods/
mod_update_json=
mod_authors=bdew
mod_credits=
mod_logo_path=

minecraft_username=Developer
extra_jvm_args=
enable_foundation_debug=false

maven_name=bdlib
maven_url=

use_access_transformer=false
is_coremod=false
coremod_includes_mod=true
coremod_plugin_class_name=

use_asset_mover=false
asset_mover_version=2.5
